#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
	colorscheme = "gruvbox"
	colorscheme_bg = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "nil"
    buffer_index_type = 4
    filetype_icon = true
    statusline_display_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#python"'
format_on_save = 1
python_file_head = [
        '#! /usr/bin/env python',
        '# -*- coding: utf-8 -*-',
                '# vim:fenc=utf-8',
        '#',
        '# Copyright © 2020 Alexandr Kozlenkov <sah4ez32@gmail.com>',
        '#',
        '# Distributed under terms of the MIT license.',
        '"""',
        '"""']
enable_typeinfo = true

[[layers]]
name = "lang#csharp"
highlight_types = 0

[[layers]]
name = "lang#go"


# [[checkers]]
# 	name = 'checkers'
# [[lang/go]]
# 	name = 'go'
# [[lang/java]]
# 	name = 'java'
# [[lang/python]]
# 	name = 'python'
# [[lang/php]]
# 	name = 'php'
# [[lang/scala]]
# 	name = 'scala'
# [[lang/c]]
# 	name = 'c'
# 
