#!/bin/bash

tty_id=$(tty)

dir=$(echo "/tmp/kcns${tty_id}")
mkdir -p $dir

if [ -f $dir/current ];
then
	cp $dir/current $dir/prev
fi

if [ "$1" == "" ];
then 
	cat $dir/current 2> /dev/null
	exit 0
fi

if [ "$1" == "-" ];
then
	mv $dir/prev $dir/current
	exit 0
fi

echo "$1" > $dir/current

exist=$(cat ${HOME}/.bash_aliases | grep kcns | wc -l)
if [ $exist -eq 0 ];
then
	echo "alias kc=\"kubectl -n\$(cat /tmp/kcns\$(tty)/current 2> /dev/null )\" # kcns" >> ${HOME}/.bash_aliases
fi
