#!/bin/bash

base_kubeconfig=${HOME}/.kube/config

usage()
{
	echo "kctx - util for set up context of kuberntes"
	echo "kctx <NAMESPACE>"
	echo "command:"
	echo " list - list available contexts"
	echo " help, -h - show help message"
	exit 0
}

if [ "$1" == "help" ];
then
	usage
fi

new_context=$1
if [ "$new_context" == "" ];
then
	egrep 'current-context' ${base_kubeconfig}
	exit 0
fi

sed -i '/current-context/d' ${base_kubeconfig}

echo 'current-context: "'$new_context'"' | tee -a ${base_kubeconfig}

tty_id=$(tty)

dir=$(echo "/tmp/kctx${tty_id}")
mkdir -p $dir

if [ -f $dir/current ];
then
	cp $dir/current $dir/prev
fi

if [ "$1" == "" ];
then 
	cat $dir/current 2> /dev/null
	exit 0
fi

if [ "$1" == "-" ];
then
	mv $dir/prev $dir/current
	exit 0
fi

echo "$1" > $dir/current
